apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: generate-key
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: sentry
        name: generate-key
        args : ["config","generate-secret-key"]
        resources: {}
      restartPolicy: Never
status: {}
