apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::130715514004:role/eksctl-test-cluster-nodegroup-ng-NodeInstanceRole-1K8QAX812PH9S
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::130715514004:role/test-role
      username: test-role
kind: ConfigMap
metadata:
  creationTimestamp: "2021-03-17T12:44:14Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "909"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 6b81f389-36e6-455c-b42b-8bfec0d282cc
