apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster
  region: us-east-1

managedNodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 1
    ssh: # use existing EC2 key
      publicKeyName: akilan-admin
  # - name: ng-mixed
  #   minSize: 3
  #   maxSize: 5
  #   instancesDistribution:
  #       maxPrice: 0.2
  #       instanceTypes: ["t2.micro","t3.micro"]
  #       onDemandBaseCapacity: 0
  #       onDemandPercentageAboveBaseCapacity: 50
  #   ssh:
  #     publicKeyName: eks-course