apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: prod-reader-role-bind
  namespace: production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prod-reader
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: eks-prod-read
