apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: admcoe-reader-role-bind
  namespace: admcoe
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admcoe-reader
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: eks-admcoe-read
